/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import Backend.CPUController;
import Backend.FileContentHandler;
import Models.Instruction;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author jimon
 */
public class main_Activity extends javax.swing.JFrame {
    
    
    private CPUController CPU;
    /**
     * Creates new form main_Activity
     */
    public main_Activity() {
        initComponents();
        
        textfieldMemorySize.setForeground(new Color(153,153,153));
        CPU = new CPUController(getPanelComponents());
        btnUploadFile.setEnabled(false);
        btnExecute.setEnabled(false);
        btnClean.setEnabled(false);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExecute = new javax.swing.JButton();
        btnUploadFile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpanelRegister1 = new javax.swing.JPanel();
        lblPC1 = new javax.swing.JLabel();
        lblIR1 = new javax.swing.JLabel();
        lblAC1 = new javax.swing.JLabel();
        lblAX1 = new javax.swing.JLabel();
        lblBX1 = new javax.swing.JLabel();
        lblCX1 = new javax.swing.JLabel();
        lblDX1 = new javax.swing.JLabel();
        textPC1 = new javax.swing.JTextField();
        textIR1 = new javax.swing.JTextField();
        textAC1 = new javax.swing.JTextField();
        textAX1 = new javax.swing.JTextField();
        textBX1 = new javax.swing.JTextField();
        textCX1 = new javax.swing.JTextField();
        textDX1 = new javax.swing.JTextField();
        label2 = new java.awt.Label();
        jpanelRegister = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        textFieldComando = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        areaComandos = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProcesos = new javax.swing.JTable();
        btnClean = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaMemoria = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCPUContentTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpanelRegister2 = new javax.swing.JPanel();
        lblPC2 = new javax.swing.JLabel();
        lblIR2 = new javax.swing.JLabel();
        lblAC2 = new javax.swing.JLabel();
        lblAX2 = new javax.swing.JLabel();
        lblBX2 = new javax.swing.JLabel();
        lblCX2 = new javax.swing.JLabel();
        lblDX2 = new javax.swing.JLabel();
        textPC2 = new javax.swing.JTextField();
        textIR2 = new javax.swing.JTextField();
        textAC2 = new javax.swing.JTextField();
        textAX2 = new javax.swing.JTextField();
        textBX2 = new javax.swing.JTextField();
        textCX2 = new javax.swing.JTextField();
        textDX2 = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnEnterMemorySize = new javax.swing.JButton();
        textfieldMemorySize = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jContentList = new javax.swing.JList<>();
        botonEstadisticas = new javax.swing.JButton();
        botomEjecutar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 255, 255));

        btnExecute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/Step-Forward-Hot-icon.png"))); // NOI18N
        btnExecute.setText("Paso a Paso");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        btnUploadFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/upload_file.png"))); // NOI18N
        btnUploadFile.setText("Upload file");
        btnUploadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadFileActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/delete.png"))); // NOI18N
        jButton1.setText("Exit");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Instructions");

        jpanelRegister1.setBackground(new java.awt.Color(204, 255, 255));
        jpanelRegister1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanelRegister1.setForeground(new java.awt.Color(255, 255, 255));

        lblPC1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPC1.setText("PC:");

        lblIR1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblIR1.setText("IR:");

        lblAC1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAC1.setText("AC:");

        lblAX1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAX1.setText("AX:");

        lblBX1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBX1.setText("BX:");

        lblCX1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCX1.setText("CX:");

        lblDX1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDX1.setText("DX:");

        textPC1.setEditable(false);
        textPC1.setBackground(new java.awt.Color(204, 255, 255));
        textPC1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textPC1.setText("         ");
        textPC1.setBorder(null);
        textPC1.setFocusable(false);

        textIR1.setEditable(false);
        textIR1.setBackground(new java.awt.Color(204, 255, 255));
        textIR1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textIR1.setText("    ");
        textIR1.setBorder(null);
        textIR1.setFocusable(false);
        textIR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIR1ActionPerformed(evt);
            }
        });

        textAC1.setEditable(false);
        textAC1.setBackground(new java.awt.Color(204, 255, 255));
        textAC1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAC1.setText("   ");
        textAC1.setBorder(null);
        textAC1.setFocusable(false);

        textAX1.setEditable(false);
        textAX1.setBackground(new java.awt.Color(204, 255, 255));
        textAX1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAX1.setText("      ");
        textAX1.setBorder(null);
        textAX1.setFocusable(false);

        textBX1.setEditable(false);
        textBX1.setBackground(new java.awt.Color(204, 255, 255));
        textBX1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textBX1.setText("    ");
        textBX1.setBorder(null);
        textBX1.setFocusable(false);

        textCX1.setEditable(false);
        textCX1.setBackground(new java.awt.Color(204, 255, 255));
        textCX1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textCX1.setText("     ");
        textCX1.setBorder(null);
        textCX1.setFocusable(false);

        textDX1.setEditable(false);
        textDX1.setBackground(new java.awt.Color(204, 255, 255));
        textDX1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textDX1.setText("     ");
        textDX1.setBorder(null);
        textDX1.setFocusable(false);

        label2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        label2.setText("BPC actual CPU2");

        javax.swing.GroupLayout jpanelRegister1Layout = new javax.swing.GroupLayout(jpanelRegister1);
        jpanelRegister1.setLayout(jpanelRegister1Layout);
        jpanelRegister1Layout.setHorizontalGroup(
            jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRegister1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelRegister1Layout.createSequentialGroup()
                        .addGroup(jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpanelRegister1Layout.createSequentialGroup()
                                    .addComponent(lblAC1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textAC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRegister1Layout.createSequentialGroup()
                                    .addComponent(lblPC1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                    .addComponent(textPC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(102, 102, 102)))
                            .addGroup(jpanelRegister1Layout.createSequentialGroup()
                                .addComponent(lblIR1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textIR1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelRegister1Layout.createSequentialGroup()
                                .addComponent(lblDX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textDX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelRegister1Layout.createSequentialGroup()
                                .addComponent(lblCX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textCX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelRegister1Layout.createSequentialGroup()
                                .addComponent(lblBX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textBX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelRegister1Layout.createSequentialGroup()
                                .addComponent(lblAX1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textAX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpanelRegister1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jpanelRegister1Layout.setVerticalGroup(
            jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRegister1Layout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPC1)
                    .addComponent(lblAX1)
                    .addComponent(textPC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIR1)
                    .addComponent(lblBX1)
                    .addComponent(textIR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAC1)
                    .addComponent(lblCX1)
                    .addComponent(textAC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelRegister1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDX1)
                    .addComponent(textDX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpanelRegister.setBackground(new java.awt.Color(204, 255, 255));
        jpanelRegister.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanelRegister.setForeground(new java.awt.Color(255, 255, 255));

        label1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        label1.setText("Pantalla");

        textFieldComando.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldComandoActionPerformed(evt);
            }
        });

        areaComandos.setColumns(20);
        areaComandos.setRows(5);
        jScrollPane6.setViewportView(areaComandos);

        jButton2.setText("Enviar Comando");

        javax.swing.GroupLayout jpanelRegisterLayout = new javax.swing.GroupLayout(jpanelRegister);
        jpanelRegister.setLayout(jpanelRegisterLayout);
        jpanelRegisterLayout.setHorizontalGroup(
            jpanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRegisterLayout.createSequentialGroup()
                .addGroup(jpanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane6))
                    .addGroup(jpanelRegisterLayout.createSequentialGroup()
                        .addGroup(jpanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelRegisterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(textFieldComando, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelRegisterLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpanelRegisterLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpanelRegisterLayout.setVerticalGroup(
            jpanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRegisterLayout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(textFieldComando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(26, 26, 26))
        );

        tablaProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Procesos", "Estados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaProcesos);

        btnClean.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/clean.png"))); // NOI18N
        btnClean.setText("Clean");
        btnClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanActionPerformed(evt);
            }
        });

        tablaMemoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pos", "Valor en memoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tablaMemoria);

        jCPUContentTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jCPUContentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PC", "Peso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jCPUContentTable);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Pos", "Valor en Disco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        jpanelRegister2.setBackground(new java.awt.Color(204, 255, 255));
        jpanelRegister2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanelRegister2.setForeground(new java.awt.Color(255, 255, 255));

        lblPC2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPC2.setText("PC:");

        lblIR2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblIR2.setText("IR:");

        lblAC2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAC2.setText("AC:");

        lblAX2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAX2.setText("AX:");

        lblBX2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblBX2.setText("BX:");

        lblCX2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCX2.setText("CX:");

        lblDX2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDX2.setText("DX:");

        textPC2.setEditable(false);
        textPC2.setBackground(new java.awt.Color(204, 255, 255));
        textPC2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textPC2.setText("         ");
        textPC2.setBorder(null);
        textPC2.setFocusable(false);

        textIR2.setEditable(false);
        textIR2.setBackground(new java.awt.Color(204, 255, 255));
        textIR2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textIR2.setText("    ");
        textIR2.setBorder(null);
        textIR2.setFocusable(false);
        textIR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIR2ActionPerformed(evt);
            }
        });

        textAC2.setEditable(false);
        textAC2.setBackground(new java.awt.Color(204, 255, 255));
        textAC2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAC2.setText("   ");
        textAC2.setBorder(null);
        textAC2.setFocusable(false);

        textAX2.setEditable(false);
        textAX2.setBackground(new java.awt.Color(204, 255, 255));
        textAX2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textAX2.setText("      ");
        textAX2.setBorder(null);
        textAX2.setFocusable(false);

        textBX2.setEditable(false);
        textBX2.setBackground(new java.awt.Color(204, 255, 255));
        textBX2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textBX2.setText("    ");
        textBX2.setBorder(null);
        textBX2.setFocusable(false);

        textCX2.setEditable(false);
        textCX2.setBackground(new java.awt.Color(204, 255, 255));
        textCX2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textCX2.setText("     ");
        textCX2.setBorder(null);
        textCX2.setFocusable(false);

        textDX2.setEditable(false);
        textDX2.setBackground(new java.awt.Color(204, 255, 255));
        textDX2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textDX2.setText("     ");
        textDX2.setBorder(null);
        textDX2.setFocusable(false);

        label3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        label3.setText("BPC actual CPU1");

        javax.swing.GroupLayout jpanelRegister2Layout = new javax.swing.GroupLayout(jpanelRegister2);
        jpanelRegister2.setLayout(jpanelRegister2Layout);
        jpanelRegister2Layout.setHorizontalGroup(
            jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRegister2Layout.createSequentialGroup()
                .addGroup(jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelRegister2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpanelRegister2Layout.createSequentialGroup()
                                    .addComponent(lblAC2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textAC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRegister2Layout.createSequentialGroup()
                                    .addComponent(lblPC2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                    .addComponent(textPC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(102, 102, 102)))
                            .addGroup(jpanelRegister2Layout.createSequentialGroup()
                                .addComponent(lblIR2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textIR2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelRegister2Layout.createSequentialGroup()
                                .addComponent(lblDX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textDX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelRegister2Layout.createSequentialGroup()
                                .addComponent(lblCX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textCX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelRegister2Layout.createSequentialGroup()
                                .addComponent(lblBX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textBX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpanelRegister2Layout.createSequentialGroup()
                                .addComponent(lblAX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textAX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpanelRegister2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jpanelRegister2Layout.setVerticalGroup(
            jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRegister2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPC2)
                    .addComponent(lblAX2)
                    .addComponent(textPC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIR2)
                    .addComponent(lblBX2)
                    .addComponent(textIR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAC2)
                    .addComponent(lblCX2)
                    .addComponent(textAC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelRegister2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDX2)
                    .addComponent(textDX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"P1", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Px", null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPU2", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"
            }
        ));
        jScrollPane7.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"P1", null, null, null, null, null, null, null, null, null, null, null, null, null},
                {"Px", null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPU1", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13"
            }
        ));
        jScrollPane8.setViewportView(jTable3);

        btnEnterMemorySize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/memory.png"))); // NOI18N
        btnEnterMemorySize.setText("Enter");
        btnEnterMemorySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterMemorySizeActionPerformed(evt);
            }
        });

        textfieldMemorySize.setText("Enter memory size");
        textfieldMemorySize.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfieldMemorySizeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textfieldMemorySizeFocusLost(evt);
            }
        });
        textfieldMemorySize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldMemorySizeActionPerformed(evt);
            }
        });
        textfieldMemorySize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldMemorySizeKeyTyped(evt);
            }
        });

        jContentList.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(jContentList);

        botonEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/chart-icon (1).png"))); // NOI18N
        botonEstadisticas.setText("Estadisticas");

        botomEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProgramImages/play.png"))); // NOI18N
        botomEjecutar.setText("Ejecutar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnEnterMemorySize)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textfieldMemorySize, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnUploadFile)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnExecute))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(54, 54, 54)
                                                .addComponent(jLabel1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botomEjecutar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpanelRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpanelRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpanelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(22, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7)
                            .addComponent(jScrollPane8))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEnterMemorySize)
                                    .addComponent(textfieldMemorySize, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnUploadFile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExecute, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClean, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botomEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(33, 33, 33)
                                .addComponent(jpanelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jpanelRegister2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jpanelRegister1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 920));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUploadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadFileActionPerformed
        
         JFileChooser chooser = new JFileChooser();
         FileNameExtensionFilter filter = new FileNameExtensionFilter("*.ASM","ASM");
         chooser.setFileFilter(filter);
         int selection = chooser.showOpenDialog(this);
         if(selection == JFileChooser.APPROVE_OPTION){
             File archivo = chooser.getSelectedFile();
             String filename = archivo.getAbsolutePath();
             try {
                 if(CPU.loadInstructions(filename, jContentList,jCPUContentTable)){
                     btnExecute.setEnabled(true);
                     btnClean.setEnabled(true);
                     CPU.executeInstruction();
                 } else{
                     JOptionPane.showMessageDialog(this, "The available memory is not enough to load the program", "Insufficient space", JOptionPane.ERROR_MESSAGE);
                     btnClean.setEnabled(true);
                 }
                 
             } catch (IOException ex) {
                 Logger.getLogger(main_Activity.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
    }//GEN-LAST:event_btnUploadFileActionPerformed

    private void textfieldMemorySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldMemorySizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldMemorySizeActionPerformed

    private void textfieldMemorySizeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldMemorySizeFocusGained
        if (textfieldMemorySize.getText().equals("Enter memory size")){
            textfieldMemorySize.setText("");
            textfieldMemorySize.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_textfieldMemorySizeFocusGained

    private void textfieldMemorySizeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfieldMemorySizeFocusLost
         if (textfieldMemorySize.getText().equals("")){
            textfieldMemorySize.setText("Enter memory size");
            textfieldMemorySize.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_textfieldMemorySizeFocusLost

    private void textfieldMemorySizeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldMemorySizeKeyTyped
        char c = evt.getKeyChar();
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_textfieldMemorySizeKeyTyped

    private void btnEnterMemorySizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterMemorySizeActionPerformed
        String memorySizeString = textfieldMemorySize.getText();
        
        if(!memorySizeString.equals("Enter memory size")){
            int memorySizeNumber= Integer.parseInt(memorySizeString);
            if(memorySizeNumber>9){
                CPU.setMemorySize(memorySizeNumber);
                btnUploadFile.setEnabled(true);
                JOptionPane.showMessageDialog(this, "The memory has been generated with a size of "+memorySizeString, "Valid value", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "The entered value must be greater than 10", "Invalid value", JOptionPane.ERROR_MESSAGE);
            }
        }else{JOptionPane.showMessageDialog(this, "The entered value cannot be empty", "Invalid value", JOptionPane.ERROR_MESSAGE);}
      
        
    }//GEN-LAST:event_btnEnterMemorySizeActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        CPU.executeInstruction();
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void btnCleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanActionPerformed
        this.dispose();
        main_Activity newFrame = new main_Activity();
        newFrame.setVisible(true);
    }//GEN-LAST:event_btnCleanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textIR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIR1ActionPerformed

    private void textIR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIR2ActionPerformed

    private void textFieldComandoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldComandoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldComandoActionPerformed

    private ArrayList<JTextField> getPanelComponents(){
        ArrayList<JTextField> list = new ArrayList<JTextField>();
        Component[] components = jpanelRegister.getComponents();
        for (Component component : components) {
            if (component.getClass().equals(JTextField.class)) {
                list.add((JTextField)component);
            }
        }
        return list;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaComandos;
    private javax.swing.JButton botomEjecutar;
    private javax.swing.JButton botonEstadisticas;
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnEnterMemorySize;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnUploadFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTable jCPUContentTable;
    private javax.swing.JList<String> jContentList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel jpanelRegister;
    private javax.swing.JPanel jpanelRegister1;
    private javax.swing.JPanel jpanelRegister2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel lblAC1;
    private javax.swing.JLabel lblAC2;
    private javax.swing.JLabel lblAX1;
    private javax.swing.JLabel lblAX2;
    private javax.swing.JLabel lblBX1;
    private javax.swing.JLabel lblBX2;
    private javax.swing.JLabel lblCX1;
    private javax.swing.JLabel lblCX2;
    private javax.swing.JLabel lblDX1;
    private javax.swing.JLabel lblDX2;
    private javax.swing.JLabel lblIR1;
    private javax.swing.JLabel lblIR2;
    private javax.swing.JLabel lblPC1;
    private javax.swing.JLabel lblPC2;
    private javax.swing.JTable tablaMemoria;
    private javax.swing.JTable tablaProcesos;
    private javax.swing.JTextField textAC1;
    private javax.swing.JTextField textAC2;
    private javax.swing.JTextField textAX1;
    private javax.swing.JTextField textAX2;
    private javax.swing.JTextField textBX1;
    private javax.swing.JTextField textBX2;
    private javax.swing.JTextField textCX1;
    private javax.swing.JTextField textCX2;
    private javax.swing.JTextField textDX1;
    private javax.swing.JTextField textDX2;
    private javax.swing.JTextField textFieldComando;
    private javax.swing.JTextField textIR1;
    private javax.swing.JTextField textIR2;
    private javax.swing.JTextField textPC1;
    private javax.swing.JTextField textPC2;
    private javax.swing.JTextField textfieldMemorySize;
    // End of variables declaration//GEN-END:variables
}
